language: php
php:
- 5.4
services:
- mysql
sudo: false
cache:
  directories:
  - vendor
before_install:
- mysql -e "create database IF NOT EXISTS kuhiw_test;" -u root
- mysql -u root kuhiw_test < database/kuhiw_test.sql
install:
- composer install
before_script:
- cp config.example.php config.php
- php -S localhost:8000 &
- sleep 3
script: vendor/bin/phpunit
env:
  global:
  - secure: dB1Y9uusJ9vaGtqmlO9WCrm4KNtZJUnCVyasqg6OnhKCkVltAAsCjMVlj5xDF6NLZHQQ7F6H29xHtSfFNyb+fEGOg3bk2MG+/J5YcRuAw72+aIqqZlbXcWxWsAsHcOaaKV+NTXuroY/SuSgB1ooSNsX7CyjuJOJPXU/DKor7Zr53TCf0SNsiuWG0eQhSm9NtgG/EhPsC6eCdjLSEiyheNQ2op7AKUIItJVHqil6FsqPXFX7pGw+vn2ExcDRO1m3zvYhSgTM+fp8UpTeDZjwAaczCZTdbgSNLgm6RNhgbLjb4ZjOBGuNZffF9gaBxxdhNuEVFIIbhhh2HyeHJ8IEOz20Hq/0j3xP+EOlAd59NvJLiuB/zMZHqm9CGkQ452u/QDwATxTapnG6JptUSN9j64U1IIJ7P+tC5vE/Xm5AFQFe7FHvPNkDO00FuCaU949rQ1cJv2oPBXP5Lo5XqDJ54zy8++s70kK6sNLQq0+VHwaZRXtYsMPzoBNvL4DpJlq0x4dLQqb96WfDXolhbYiGLwDTRiDH+yCxz9ij9eTqcHypPqyG6zz44Cv7h8VZMjhaTvx0NdDx9aUAMsUlAjezpRuYoPzrd2gonEnXigy27sVlV/yjVGSmIsmwXnKJcCbLcOEmVP1n/4MT0ONPbgNxbuQFnomB+5WUOwp5W49QRktU=
  - secure: uMNlUerce5nwpHpS6u7k1b6CCOEcM3lj1BZQWshNwTxHvd29nhPjmqsdZPuoR+BTTHN9N/dkJ54DMzmU7IK+L5HgyDXR1Mmg6Ve8oSh0XoRwZFYE7WHqgoJp8pUq572OXqUfuRopERMhTTiREse4JlIgPNF9R9kFoIUAkbXHi3Xrg6uy3a2mJJ/e7VE3BFvQe1AKBwj4PRnzjaFGW+t8OqTGZe/SSSAeYmdtZ01naFAN0PxjAFCDjqsLsydgdH8sFZdzXN2sViMOTi58V1fEUrsVH+NVqhFnI/9RV+XDg0GqKLu5v/FSKXoe263ugbtVvp8z2xhrly825j30L/nKqS0sJplbWEA2EdbMju1K6B4sykhGv8sgQBy7BzgZFvFAHqtsu2IqORXkB4/D4x5w3czdLS+pMB2IhW3nH3L5KZ2FQkdJVplj/5W/TbnZ5y0dzQ9n9ER3cBfEq/W9iBr/V8CdBA5xoQoN50WGFnU8LAsfnDxy/ePT89AbRvFAEHctneKl3Ug5yzmw/NOHWvZH0b0myusTcIDK3QKv+sznJn3N6XT6JLbGqXNrrw420IuQVV4/QS/ZrpGblcMg+x/25s4fgcqfNQsYOb36VQ/KZ6OnDKkwN7uL9U980/dNLWOJtABxxogimDCfm57SSJ7KsqNQxXK0wQ0jZKCzZaubi8o=
  - secure: DCWZlVU6sPnPRVpuWRcOFdctcgfXbHIHZw8ur6JUao+N8Ya6N059gbnDQYWF4KI6PGzeJFXJ7tazffXndLnjrjCYGVz6RKfmjl74DTPj4hT8sTZvSLiIutZIfMJ1TfHRtucmnLX0OaMI2RNwtyYX0Wtqufbg1VNzsaMovupE12FvRh8rGGtGJMPtRHBN7QZ/PzWQ2dAPeCHO55mKZ7sYOw8uhtKpV8Hq7YzHbbO53Yv8octTt6IGSAlVa42bJGLauwPu13ChIeFe/5kr2bxQXmMVMuWFYDGfSK2ebH6/fxxP1XCACxQKCU/l4QDdhTx2NDktU2TaDTw1yJH4Czu7lTqln2yCriqbk5dkAVXW3EWXJYju4BrFj1NwmjKliygOFiUclBWBJ5Aji2xBDUgnswbvWqibJN+wdm0CWN3xlrpkMj/Q4GnAlkTqiTxtPAc1neAs3uNvLW5kHib8QoRppaspqB/0vMhnCxP1rlx/cRApnspwMykCiSXzoDXNwqFuLchfSd06x+qVFGJCmS3Eb0z6jco2MoOb7pUJx0JxUmfqAY3tJIn3Mj88xmOCViitZlUSZFCCHE+uZuNd2ANvdAEF8aC/Rk2UDKxjoVtztzLYQco4bAOl4Zds0FbkIdISs+b6imOYJrAcDDAB9u8M3Qpk9L0TiLalXihUQ0bJNBo=
  - secure: rfRXXuENGRCICeeov9HkX2H5F+g6JFSzxHb+Iv5osK3W4zWqRBlq6r8/LfB9TRd9SRrR2q2eKQZkXUZWScgpo5240f1vbdz+8hntOUg4ySRwtD1gjA2+zLwHMKvWtXRLfM+YGUmt3z+W5SJ6UcGkm71RMWL1D8k0RHbu8pvYBHP66dikbYs6xIGjjEnbJlM5cT3E7OM+e6wIuPC727Z2RcGupiM7M03I0Jigd8qKe6+c/4Dg4AyCktL6itYOJbCwiU9sFDRNOHOwgVbR66nyoVd6O6675xChfHpbvjfeFz78dpwyuZCMY8KvlsusjOYZrgBU0cvU9QK3tGH7riKPzuqhO7v0xI10rpleU8CrFD8ZUYxE2dVfUl4964HfMS5fGhvud7QHvLuk51WFRV04dfUUPj+ihOhxFXIbFl5Py4YBokaC//F2ceQAbMofILO1eepy3gtPHATEWmhCczZX99o+8S/uLxGOkw61ptcLQUlz6j7LkO1zKHHS5AVeZkqs7c6ASz2xlzhXBAC3osYnzFfj2a9YNQTOgiwG4mGs3CoFKhEcrYcXkvIcgQBqRuNLGXQpoIaqW9fMU45PMRmWMCWwvVxXknkHZAOY7WpwQ5V3mkQopRlP/lyGNVsqiox9mlUgPm+yKaJBgc0OihSSsGqnpvSsCp3g+0DRGxxsLss=
after_success:
- npm install
- gulp deploy --user $FTP_USER --password $FTP_PASSWORD --host $FTP_HOST --path $FTP_PATH
