language: php

php:
  - 5.4

services:
  - mysql

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - vendor

before_install:
  - mysql -e "create database IF NOT EXISTS kuhiw_test;" -u root
  - mysql -u root kuhiw_test < database/kuhiw_test.sql

# install dependencies
install:
  - composer install

before_script:
  - cp config.example.php config.php
  - php -S localhost:8000 &
  - sleep 3

script: vendor/bin/phpunit

env:
  global:
    - secure: BpfrZAxyaWtRxVWla//uCdGQn3tyJ9jJHh3P+gVSmCtMapNWZ76bZ8zN39+EpZ8kAwXxx6HYRQNeJWfVsm7L6oipa4ZOioaHciNs0Tj8u/o1mZEtJbtU/BKJMR3nYvhiKSfj4hF8yBdiThPjWoCNuu2OXADs0bKmEJJkx4nrbNWJkVK9pVuc1oTu0nikv5mP5Gw/rBSrvtopqSHvhma1W5YiKTpn8lM9KMBZasAyQMw53LCWwSCM7ZshWdjXVj3ch+kX6oVHpo2ArKEZeSgMbzo8/YHU+t9MPj8320e2HPSzPp6YTd33yN3By3QX15HhFDKt2CtZEXVvOwrw9UhA6W4jZy3bkjzUZyWIuWnGkSsFwJrseQsnk5D3dhKYCOxP3zUUhxY3u5Z1zIsz0sjCZYWOCimacvzj3myCfQBWFu9i9QIEjm4r9wMhld9/97I3r079GlWDuHc8N3xK2W2i9/ZcIcmvTiweO9GWyb1i8WT7nrAvlUCqqGo9jHpgSV0L3YI10LdgbjZmHHHHiHK6cgN+flYhKZ6CNheCeTKQvmKj+2BOMlYpsKp8+FXqcdyq74lJqojzH3TS8VRKLZ8G03g2atP9wk2vDFvtbxccpFclk8o5gZOEAX7m8PhGcP46oT3POdasFJZbYhluyq5DuBd/t6aB+xqgdiPD1OgnJRA=
    - secure: GpeBes8gc1weenpV+qwtyIBtvIc9EnokfCbBQ6IWMa3OHT8WOk2IoDbL531AmusfEInEwPsjub21vhXBq3BeAtSuHPYQP5T62Sht4wi6YA4MKKZqjkzkK1gcxRNShItz4fPigfBzqi6C32nJfrEHAYAyJGPy7gQlBcLMScoEQ1dEww23XMZ8C+OdPSmVD9T9dJCamzv59nfSESC7PWCgEi0fPHlVFek10pfmvjajy65sp0QTJv4y5e07kh4fsyoGVXvlljEtk816oWnOfz3wfWyX4D+kPfViWUD3DjOwMCHRZny/jjzB81DPr8nzi6nkhzS1q3TE3JLpY0mdWJAFuLWFU+Z5cQ3wp8kS4PJjc5oL/fb37N62a1Pa5CUcVAn7SxM1APv/2utONtdWiZP+shgDqJVWi8edOuDxS5z0X4toP5ZLO+C5xwHQFUi5vSunPl/ZWV0f376JDPKx4jCIB4J5tnpaT1JD4s1MAXDCP8bQCKAj3/UcisQcWvPFcxfgTponPDpoJ/AFzkJChHs3i0yI9qMSURl842CItLZ2jAuRIxFALYcCGRDA7FSvE9Cm0M+1B8yGs/ffYodPnQe1m2bMTcV548VwHqlRzmHNpf6M9+ubh8cWZVDJ+EK9DvUhWfX/pDkBnRKGSxgZk4iubyjo9ISh2iYDt7vyM9IEVqY=
    - secure: FvbxN0owEvKE5FoKig2HPXXLBwGLZa7GVP8/s1IBMtG+unt1if2pO/+9dF1CiNVtkK+H7NtnxaI3rt/iakSsQbR28uLNR+wN054FWW8A5XWqRuVgj3UpETgtlmmjkPXnAJqLCiEAsJDqDnGUSwwpozD0rMU/Csv7mc4O7H6kLpnuwvNq7bPWgQIyV3fmUnUjkkEiw0o+tz16WWay1RqUAaha5s2+idlbW36AoSjTt9JXdQJ904BuJ0y3GcH4Dec5a2cUPaEgIVslv6Hc364IOD80Hq1HcWrWiFYanIIuY5EfkBIf6S5rxGs7yRi7nf4wg3w0WCoTjPGDAXbr+ihGb4Z8BGhujO6rdH3XZ8afRsr+e2JWQd3r1g9uNzIht36ve5vZLltbP5/GHQh6tYnsiLOOQL2Iv0cb+fFDsCZG5XtXu8KFStnN4nSdPnvB0439YhZqAajNywhnXyZM1uMbIHm7rjskwG5NDY5UR8QLyYbXB4Dh0NsmIUAGagz0gQOEkoTvYXAGWIvazypiPPnv7BIAu0Wy+k617xsDJfZNVd0FWehBXZxRzl1jIW6KuTBxY2wrUqkCs1Rv1n7nAIN7KsasfudCGVBxM3MkDt9Y1NRM4PZjAgJgalZQyp4Wch84LNT5hpradzt0huKwZ5CBEFXX5dTIOd4CbNYDxgVg7cQ=

after_success:
  - cd ..
  - cp -R kuhiw-webservice kuhiw
  - cd kuhiw
  - rm -rf .git
  - composer install --no-dev
  - cd ..
  - find {.??,}* -type f -exec curl -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {} ftp://$BASE_URL\{\} \;