language: php
php:
- 5.4
services:
- mysql
sudo: false
cache:
  directories:
  - vendor
before_install:
- mysql -e "create database IF NOT EXISTS kuhiw_test;" -u root
- mysql -u root kuhiw_test < database/kuhiw_test.sql
install:
- composer install
before_script:
- cp config.example.php config.php
- php -S localhost:8000 &
- sleep 3
script: vendor/bin/phpunit
